name: Create DynamoDB Table

on:
  push:
    branches: [main]  # Trigger on pushes to the main branch

jobs:
  create-table:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BETA_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BETA_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create DynamoDB stack
        run: aws cloudformation create-stack --stack-name MyDynamoDBStack --template-body file://dynamodb-template.yaml --capabilities CAPABILITY_AUTO_EXPAND

  deploy-dev:
    # needs: test  # Ensure test is successful before deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      # - run: pip install -r requirements.txt
      # - run : yes | sam delete --stack-name dev-stack --region us-east-1 --no-prompts
      - run: pip install aws-sam-cli
      - run: sam build
      - run: sam deploy --no-confirm-changeset --stack-name dev-stack --region us-east-1  # Specify dev stack and region
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BETA_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BETA_ACCESS_KEY }}